spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create


application:
  security:
    jwt:
      secret: kvKHL5jkO4wrWWzyH+2fEhOnBp/a9nvwDD2XTE8GFmE=
      accessExpiresIn: 900
      refreshExpiresIn: 86400

